name: Generate Datas

on:
  schedule:
    - cron: "0 8,20 * * *" # Executa às 8h e 20h
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Cria o diretório de saída, se não existir
      - name: Create output directory
        run: mkdir -p dist

      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Christian-valino
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Deploy para a branch de saída
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Confirmação de execução bem-sucedida
      - name: Job completed
        run: echo "Workflow completed successfully!"
